name: twenty_four_hours
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  #cloud_firestore: ^0.7.3
  #firebase_auth: ^0.5.11
  #firebase_database: ^1.0.1
  #firebase_storage: ^0.3.7



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  font_awesome: ^4.7.0
  font_awesome_flutter: ^7.0.0
  http: ^0.11.3+16
  image: ^2.0.3
  intl: ^0.15.6
  location: ^1.3.4
  image_picker: ^0.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
          weight: 400

    - family: Audiowide
      fonts:
        - asset: fonts/Audiowide-Regular.ttf
          weight: 400

    - family: ExoBlack
      fonts:
        - asset: fonts/Exo-Black.ttf
        - asset: fonts/Exo-BlackItalic.ttf
          weight: 400
    - family: ExoBold
      fonts:
        - asset: fonts/Exo-Bold.ttf
        - asset: fonts/Exo-ExtraBold.ttf
        - asset: fonts/Exo-ExtraBoldItalic.ttf
          weight: 400
    - family: ExoLight
      fonts:
        - asset: fonts/Exo-ExtraLight.ttf
        - asset: fonts/Exo-Light.ttf
        - asset: fonts/Exo-ExtraLightItalic.ttf
          weight: 400
    - family: Exo
      fonts:
        - asset: fonts/Exo-Regular.ttf
        - asset: fonts/Exo-Italic.ttf
          weight: 400
    - family: GochiHand
      fonts:
        - asset: fonts/GochiHand-Regular.ttf
          weight: 400
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata-Bold.ttf
        - asset: fonts/Inconsolata-Regular.ttf
          weight: 400
    - family: Jua
      fonts:
        - asset: fonts/Jua-Regular.ttf
          weight: 400
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower.ttf
          weight: 400
    - family: Monoton
      fonts:
        - asset: fonts/Monoton-Regular.ttf
          weight: 400
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
          weight: 400
    - family: PassionOne
      fonts:
        - asset: fonts/PassionOne-Regular.ttf
          weight: 400
    - family: PoorStory
      fonts:
        - asset: fonts/PoorStory-Regular.ttf
          weight: 400



  uses-material-design: true
  assets:
    - images/ic_launcher.png
    - images/hbot.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.


  # To add assets to your application, add an assets section, like this:
  # assets:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  

  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
